"""Write a compiled Mesh to Wavefront OBJ + MTL.

OBJ/MTL is one of the two formats Roblox's 3D Importer accepts (the other is
FBX). The .mtl file carries one material per distinct colour so the model looks
right in Blender and other tools; see README for how colours behave on import.
"""

from __future__ import annotations

import os


def write_obj(mesh, out_dir, name):
    """Write <name>.obj and <name>.mtl into out_dir. Returns (obj_path, tris)."""
    os.makedirs(out_dir, exist_ok=True)
    safe = _safe_filename(name)
    obj_path = os.path.join(out_dir, safe + ".obj")
    mtl_path = os.path.join(out_dir, safe + ".mtl")

    _write_mtl(mtl_path, mesh.materials)

    lines = [
        "# Generated by promptmesh (https://github.com/MattG241/3d-model-maker)",
        "mtllib %s.mtl" % safe,
        "o %s" % safe,
    ]
    for v in mesh.verts:
        lines.append("v %.5f %.5f %.5f" % v)

    for key, faces in mesh.groups.items():
        lines.append("usemtl %s" % key)
        for (a, b, c) in faces:
            lines.append("f %d %d %d" % (a + 1, b + 1, c + 1))  # OBJ is 1-based

    with open(obj_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    return obj_path, mesh.triangle_count


def _write_mtl(path, materials):
    lines = ["# Generated by promptmesh"]
    for key, (r, g, b) in materials.items():
        fr, fg, fb = r / 255.0, g / 255.0, b / 255.0
        lines += [
            "newmtl %s" % key,
            "Ka %.4f %.4f %.4f" % (fr * 0.2, fg * 0.2, fb * 0.2),
            "Kd %.4f %.4f %.4f" % (fr, fg, fb),
            "Ks 0.0000 0.0000 0.0000",
            "d 1.0",
            "illum 1",
            "",
        ]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def _safe_filename(name):
    safe = "".join(c if (c.isalnum() or c in " -_") else "_" for c in name).strip()
    safe = safe.replace(" ", "_")
    return safe or "model"
