"""Write a compiled Mesh to Wavefront OBJ + MTL.

OBJ/MTL is one of the two formats Roblox's 3D Importer accepts (the other is
FBX). The .mtl file carries one material per distinct colour so the model looks
right in Blender and other tools; see README for how colours behave on import.
"""

from __future__ import annotations

import os


def build_obj_mtl(mesh, name):
    """Return (obj_text, mtl_text, triangle_count) for a compiled mesh."""
    safe = _safe_filename(name)

    mtl_lines = ["# Generated by promptmesh"]
    for key, (r, g, b) in mesh.materials.items():
        fr, fg, fb = r / 255.0, g / 255.0, b / 255.0
        mtl_lines += [
            "newmtl %s" % key,
            "Ka %.4f %.4f %.4f" % (fr * 0.2, fg * 0.2, fb * 0.2),
            "Kd %.4f %.4f %.4f" % (fr, fg, fb),
            "Ks 0.0000 0.0000 0.0000",
            "d 1.0",
            "illum 1",
            "",
        ]
    mtl_text = "\n".join(mtl_lines) + "\n"

    obj_lines = [
        "# Generated by promptmesh (https://github.com/MattG241/3d-model-maker)",
        "mtllib %s.mtl" % safe,
        "o %s" % safe,
    ]
    for v in mesh.verts:
        obj_lines.append("v %.5f %.5f %.5f" % v)
    for key, faces in mesh.groups.items():
        obj_lines.append("usemtl %s" % key)
        for (a, b, c) in faces:
            obj_lines.append("f %d %d %d" % (a + 1, b + 1, c + 1))  # OBJ is 1-based
    obj_text = "\n".join(obj_lines) + "\n"

    return obj_text, mtl_text, mesh.triangle_count


def write_obj(mesh, out_dir, name):
    """Write <name>.obj and <name>.mtl into out_dir. Returns (obj_path, tris)."""
    os.makedirs(out_dir, exist_ok=True)
    safe = _safe_filename(name)
    obj_text, mtl_text, tris = build_obj_mtl(mesh, name)
    obj_path = os.path.join(out_dir, safe + ".obj")
    with open(obj_path, "w", encoding="utf-8") as f:
        f.write(obj_text)
    with open(os.path.join(out_dir, safe + ".mtl"), "w", encoding="utf-8") as f:
        f.write(mtl_text)
    return obj_path, tris


def _safe_filename(name):
    safe = "".join(c if (c.isalnum() or c in " -_") else "_" for c in name).strip()
    safe = safe.replace(" ", "_")
    return safe or "model"
